// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyWebAPI.Migrations
{
    [DbContext(typeof(RentACarContext))]
    [Migration("20250112160650_UpdateTimestampColumns")]
    partial class UpdateTimestampColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Autoturism", b =>
                {
                    b.Property<int>("AutoturismId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AutoturismId"));

                    b.Property<bool>("Disponibil")
                        .HasColumnType("boolean");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumarInmatriculare")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TarifPeZi")
                        .HasColumnType("numeric");

                    b.HasKey("AutoturismId");

                    b.HasIndex("NumarInmatriculare")
                        .IsUnique();

                    b.ToTable("Autoturisme");
                });

            modelBuilder.Entity("Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CNP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClientId");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("Inchiriere", b =>
                {
                    b.Property<int>("InchiriereId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InchiriereId"));

                    b.Property<int>("AutoturismId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CostTotal")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DataEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observatii")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InchiriereId");

                    b.HasIndex("AutoturismId");

                    b.HasIndex("ClientId");

                    b.ToTable("Inchirieri");
                });

            modelBuilder.Entity("Inchiriere", b =>
                {
                    b.HasOne("Autoturism", "Autoturism")
                        .WithMany("Inchirieri")
                        .HasForeignKey("AutoturismId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client", "Client")
                        .WithMany("Inchirieri")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autoturism");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Autoturism", b =>
                {
                    b.Navigation("Inchirieri");
                });

            modelBuilder.Entity("Client", b =>
                {
                    b.Navigation("Inchirieri");
                });
#pragma warning restore 612, 618
        }
    }
}
